services:
  mongodb:
    image: mongo
    container_name: MieTechCatalogDB
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build: .
    container_name: MieTechCatalogAPI
    ports:
      - 3000:3000
    environment:
      MONGO_URI: ${MONGO_URI}
      PHOTOS_DIRECTORY: /app/uploads
      PORT: ${PORT}
    volumes:
      - ./app_data:/app/uploads

volumes:
  mongodb_data:
  app_data:
